name:       eventless
version:    0.1.0.1
github:     "reisen/eventless"
license:    MIT
author:     "Reisen"
maintainer: "reisen@morphism.org"
copyright:  "2018 Reisen"

extra-source-files:
    - README.md

description: Event Sourcing with automatic snapshotting.

ghc-options:
    -Wall
    -fwarn-tabs
    -fwarn-unused-imports
    -fwarn-missing-signatures
    -fwarn-name-shadowing
    -fwarn-incomplete-patterns

dependencies:
    - base
    - aeson
    - containers
    - data-default-class
    - mtl
    - protolude
    - sqlite-simple
    - text
    - time

default-extensions:
    - BangPatterns
    - ConstraintKinds
    - DataKinds
    - DeriveDataTypeable
    - DeriveGeneric
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GADTs
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - MultiParamTypeClasses
    - NoImplicitPrelude
    - OverloadedStrings
    - PatternSynonyms
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeFamilyDependencies
    - TypeOperators
    - ViewPatterns

library:
  source-dirs: src
